//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recycling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constituent
    {
        public Constituent()
        {
            this.LocatedIns = new HashSet<LocatedIn>();
            this.ProductHasConstituents = new HashSet<ProductHasConstituent>();
        }
    
        public string ConstituentName { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<LocatedIn> LocatedIns { get; set; }
        public virtual ICollection<ProductHasConstituent> ProductHasConstituents { get; set; }
    }
}
