//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recycling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocatedIn
    {
        public string ConstituentName { get; set; }
        public string RegionName { get; set; }
        public string Classification { get; set; }
        public string Recyclability { get; set; }
    
        public virtual Constituent Constituent { get; set; }
        public virtual Region Region { get; set; }
    }
}
