//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recycling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.LocatedIns = new HashSet<LocatedIn>();
        }
    
        public string RegionName { get; set; }
    
        public virtual ICollection<LocatedIn> LocatedIns { get; set; }
    }
}
